from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
import os
from datetime import datetime


def create_docx(document_data, title="AI Generated Document"):

    folder = "generated_docs"
    os.makedirs(folder, exist_ok=True)

    filename = f"AI_Document_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"

    filepath = os.path.join(folder, filename)

    doc = Document()

    # Page setup
    section = doc.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.8)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)


    # Default font
    normal_style = doc.styles["Normal"]
    normal_style.font.name = "Calibri"
    normal_style.font.size = Pt(11)


    # Title
    heading = doc.add_heading(title, level=1)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER


    # Add sections
    for section_title, section_content in document_data.items():

        # Heading
        doc.add_heading(section_title, level=2)


        # List content
        if isinstance(section_content, list):

            for item in section_content:

                paragraph = doc.add_paragraph(
                    style="List Bullet"
                )

                paragraph.paragraph_format.left_indent = Inches(0.5)
                paragraph.paragraph_format.first_line_indent = Inches(-0.25)
                paragraph.paragraph_format.space_after = Pt(6)

                paragraph.add_run(item)


        # Normal text
        else:

            paragraph = doc.add_paragraph()

            paragraph.paragraph_format.first_line_indent = Inches(0.3)
            paragraph.paragraph_format.space_after = Pt(8)
            paragraph.paragraph_format.line_spacing = 1.15

            paragraph.add_run(section_content)



    # Footer
    footer = doc.sections[0].footer.paragraphs[0]
    footer.text = "Generated by Autonomous AI Agent"
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER


    doc.save(filepath)

    return filepath